all: ejemplo_signal0 ejemplo_signal1 ejemplo_signal2 ejemplo_signal3 ejemplo_signal4 ejemplo0_un_fork ejemplo1_dos_forks ejemplo2_bucle_forks ejemplo3_herencia_fork ejemplo4_herencia_fork ejemplo5_exit_fork ejemplo6_par_wait ejemplo7_proceso_muta ejemplo8_funcion_vs_exec ejemplo9_funcion_vs_exec ejemplo10_mils ejemplo11_pids_hermanos ejemplo12_pids_hermanos_secuencial ejemplo13_alt_pids_hermanos_orden_inverso ejemplo13_pids_hermanos_orden_inverso ejemplo14_pids_hermanos_orden_inverso_signal_hermanos

ejemplo_signal0: ejemplo_signal0.c
	gcc -o ejemplo_signal0 ejemplo_signal0.c

ejemplo_signal1: ejemplo_signal1.c
	gcc -o ejemplo_signal1 ejemplo_signal1.c

ejemplo_signal2: ejemplo_signal2.c
	gcc -o ejemplo_signal2 ejemplo_signal2.c

ejemplo_signal3: ejemplo_signal3.c
	gcc -o ejemplo_signal3 ejemplo_signal3.c

ejemplo_signal4: ejemplo_signal4.c
	gcc -o ejemplo_signal4 ejemplo_signal4.c

ejemplo0_un_fork: ejemplo0_un_fork.c
	gcc -o ejemplo0_un_fork ejemplo0_un_fork.c

ejemplo1_dos_forks: ejemplo1_dos_forks.c
	gcc -o ejemplo1_dos_forks ejemplo1_dos_forks.c

ejemplo2_bucle_forks: ejemplo2_bucle_forks.c
	gcc -o ejemplo2_bucle_forks ejemplo2_bucle_forks.c

ejemplo3_herencia_fork: ejemplo3_herencia_fork.c
	gcc -o ejemplo3_herencia_fork ejemplo3_herencia_fork.c

ejemplo4_herencia_fork: ejemplo4_herencia_fork.c
	gcc -o ejemplo4_herencia_fork ejemplo4_herencia_fork.c

ejemplo5_exit_fork: ejemplo5_exit_fork.c
	gcc -o ejemplo5_exit_fork ejemplo5_exit_fork.c

ejemplo6_par_wait: ejemplo6_par_wait.c
	gcc -o ejemplo6_par_wait ejemplo6_par_wait.c

ejemplo7_proceso_muta: ejemplo7_proceso_muta
	gcc -o ejemplo7_proceso_muta ejemplo7_proceso_muta.c

ejemplo8_funcion_vs_exec: ejemplo8_funcion_vs_exec.c
	gcc -o ejemplo8_funcion_vs_exec ejemplo8_funcion_vs_exec.c

ejemplo9_funcion_vs_exec: ejemplo9_funcion_vs_exec.c
	gcc -o ejemplo9_funcion_vs_exec ejemplo9_funcion_vs_exec.c

ejemplo10_mils: ejemplo10_mils.c
	gcc -o ejemplo10_mils ejemplo10_mils.c

ejemplo11_pids_hermanos: ejemplo11_pids_hermanos.c
	gcc -o ejemplo11_pids_hermanos ejemplo11_pids_hermanos.c

ejemplo12_pids_hermanos_secuencial: ejemplo12_pids_hermanos_secuencial.c
	gcc -o ejemplo12_pids_hermanos_secuencial ejemplo12_pids_hermanos_secuencial.c

ejemplo13_alt_pids_hermanos_orden_inverso: ejemplo13_alt_pids_hermanos_orden_inverso.c
	gcc -o ejemplo13_alt_pids_hermanos_orden_inverso ejemplo13_alt_pids_hermanos_orden_inverso.c

ejemplo13_pids_hermanos_orden_inverso: ejemplo13_pids_hermanos_orden_inverso.c
	gcc -o ejemplo13_pids_hermanos_orden_inverso ejemplo13_pids_hermanos_orden_inverso.c

ejemplo14_pids_hermanos_orden_inverso_signal_hermanos: ejemplo14_pids_hermanos_orden_inverso_signal_hermanos.c
	gcc -o ejemplo14_pids_hermanos_orden_inverso_signal_hermanos ejemplo14_pids_hermanos_orden_inverso_signal_hermanos.c
