all: jerarquia1 jerarquia2 signals

jerarquia1:jerarquia1.c
	gcc -o jerarquia1 jerarquia1.c

jerarquia2:jerarquia2.c
	gcc -o jerarquia2 jerarquia2.c

signals:signals.c
	gcc -o signals signals.c
clean:
	rm -rf jerarquia1 jerarquia2 signals
