all: ejemplo_signal ejemplo_signal2 alarms signalPerdido eventos eventos2

eventos:eventos.c
	gcc -o eventos eventos.c

eventos2:eventos2.c
	gcc -o eventos2 eventos2.c

ejemplo_signal:ejemplo_signal.c
	gcc -o ejemplo_signal ejemplo_signal.c

ejemplo_signal2:ejemplo_signal2.c
	gcc -o ejemplo_signal2 ejemplo_signal2.c

alarms:alarm1 alarm2 alarm3 alarm4

alarm1:ejemplo_alarm1.c
	gcc -o alarm1 ejemplo_alarm1.c 
alarm2:ejemplo_alarm2.c
	gcc -o alarm2 ejemplo_alarm2.c 
alarm3:ejemplo_alarm3.c
	gcc -o alarm3 ejemplo_alarm3.c 
alarm4:ejemplo_alarm4.c
	gcc -o alarm4 ejemplo_alarm4.c 
signalPerdido:signalPerdido.c
	gcc -o signalPerdido signalPerdido.c 

clean:
	rm -rf alarm1 alarm2 alarm3 alarm4 ejemplo_waitpid ejemplo_waitpid2 signalPerdido

